from typing import TypedDict


class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        - question: The question asked by the user.
        - generation: The answer generated by the model.
        - web_Search: Whether to add web search.
        - documents: list of documents.
    """

    question: str
    generation: str
    web_Search: bool
    documents: list[str]
